# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/gx-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amlogic/gx-common

PRODUCT_COPY_FILES += \
    vendor/amlogic/gx-common/proprietary/lib/vendor.amlogic.hardware.droidvold@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.amlogic.hardware.droidvold@1.0.so \
    vendor/amlogic/gx-common/proprietary/product/lib/libamavutils.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libamavutils.so \
    vendor/amlogic/gx-common/proprietary/vendor/bin/hdmicecd:$(TARGET_COPY_OUT_VENDOR)/bin/hdmicecd \
    vendor/amlogic/gx-common/proprietary/vendor/bin/hw/android.hardware.drm@1.1-service.widevine:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.1-service.widevine \
    vendor/amlogic/gx-common/proprietary/vendor/bin/systemcontrol:$(TARGET_COPY_OUT_VENDOR)/bin/systemcontrol \
    vendor/amlogic/gx-common/proprietary/vendor/etc/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.conf \
    vendor/amlogic/gx-common/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.widevine.rc \
    vendor/amlogic/gx-common/proprietary/vendor/etc/init/hdmicecd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hdmicecd.rc \
    vendor/amlogic/gx-common/proprietary/vendor/etc/init/init.hbg.remote.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.hbg.remote.rc \
    vendor/amlogic/gx-common/proprietary/vendor/etc/init/systemcontrol.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/systemcontrol.rc \
    vendor/amlogic/gx-common/proprietary/product/etc/permissions/droidlogic.software.core.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/droidlogic.software.core.xml \
    vendor/amlogic/gx-common/proprietary/vendor/etc/permissions/droidlogic.tv.software.core.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/droidlogic.tv.software.core.xml \
    vendor/amlogic/gx-common/proprietary/vendor/etc/remote.txt:$(TARGET_COPY_OUT_VENDOR)/etc/remote.txt \
    vendor/amlogic/gx-common/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/amlogic/gx-common/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/amlogic/gx-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/amlogic/gx-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/amlogic/gx-common/proprietary/vendor/lib/firmware/video/h264_enc.bin:$(TARGET_COPY_OUT_VENDOR)/lib/firmware/video/h264_enc.bin \
    vendor/amlogic/gx-common/proprietary/vendor/lib/firmware/video/video_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/lib/firmware/video/video_ucode.bin \
    vendor/amlogic/gx-common/proprietary/vendor/lib/hw/audio.primary.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.amlogic.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/hw/camera.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.amlogic.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/hw/gatekeeper.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.amlogic.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/hw/hdmi_cec.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hdmi_cec.amlogic.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/hw/memtrack.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.amlogic.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/hw/power.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/power.amlogic.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/hw/thermal.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/thermal.amlogic.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libHwAudio_dcvdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libHwAudio_dcvdec.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libHwAudio_dtshd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libHwAudio_dtshd.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libOmxAudio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxAudio.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libOmxBase.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxBase.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libOmxCore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxCore.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libOmxCoreSw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxCoreSw.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libOmxVideo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxVideo.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libam_adp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libam_adp.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libamadec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libamadec.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libamaudioutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libamaudioutils.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libamavutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libamavutils.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libamgralloc_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libamgralloc_ext.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libamlaudiorc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libamlaudiorc.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libdatachunkqueue_alt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdatachunkqueue_alt.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libdisplaysetting.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdisplaysetting.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libdra.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdra.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libdroidaudiospdif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdroidaudiospdif.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libdtvad.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdtvad.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libfbc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfbc.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libfpscalculator_alt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfpscalculator_alt.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libhbg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhbg.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libhbgdecode.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhbgdecode.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libhdmicec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhdmicec.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libhdmicec_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhdmicec_jni.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libicuuc_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libicuuc_vendor.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libms12api.so:$(TARGET_COPY_OUT_VENDOR)/lib/libms12api.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libnano.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnano.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libomx_av_core_alt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libomx_av_core_alt.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libomx_clock_utils_alt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libomx_clock_utils_alt.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libomx_framework_alt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libomx_framework_alt.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libomx_timed_task_queue_alt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libomx_timed_task_queue_alt.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libomx_worker_peer_alt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libomx_worker_peer_alt.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libpqcontrol.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpqcontrol.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libremotecontrol_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libremotecontrol_jni.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libremotecontrolserver.so:$(TARGET_COPY_OUT_VENDOR)/lib/libremotecontrolserver.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libstagefright_soft_amsoftdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_soft_amsoftdec.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrighthw.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libsystemcontrol_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsystemcontrol_jni.so \
    vendor/amlogic/gx-common/proprietary/lib/libsystemcontrol_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsystemcontrol_jni.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libsystemcontrolclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsystemcontrolclient.so \
    vendor/amlogic/gx-common/proprietary/lib/libsystemcontrolclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsystemcontrolclient.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libsystemcontrolservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsystemcontrolservice.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libthreadworker_alt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthreadworker_alt.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libtvbinder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtvbinder.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libwvhidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvhidl.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libavl.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libavl.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libbalance.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libbalance.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libdbx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libdbx.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libgeq.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libgeq.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libhpeqwrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libhpeqwrapper.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libms12dapwrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libms12dapwrapper.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libsrswrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libsrswrapper.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libtreblebasswrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libtreblebasswrapper.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libvirtualsurround.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libvirtualsurround.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/soundfx/libvirtualx.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libvirtualx.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/vendor.amlogic.hardware.droidvold@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.droidvold@1.0.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/vendor.amlogic.hardware.hdmicec@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.hdmicec@1.0.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/vendor.amlogic.hardware.miracast_hdcp2@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.miracast_hdcp2@1.0.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/vendor.amlogic.hardware.remotecontrol@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.remotecontrol@1.0.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/vendor.amlogic.hardware.screencontrol@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.screencontrol@1.0.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/vendor.amlogic.hardware.systemcontrol@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.systemcontrol@1.0.so \
    vendor/amlogic/gx-common/proprietary/lib/vendor.amlogic.hardware.systemcontrol@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.amlogic.hardware.systemcontrol@1.0.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/vendor.amlogic.hardware.systemcontrol@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.systemcontrol@1.1.so \
    vendor/amlogic/gx-common/proprietary/lib/vendor.amlogic.hardware.systemcontrol@1.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.amlogic.hardware.systemcontrol@1.1.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/vendor.amlogic.hardware.tvserver@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.amlogic.hardware.tvserver@1.0.so

PRODUCT_PACKAGES += \
    libge2d \
    droidlogic-res \
    droidlogic-tv \
    droidlogic

ifneq ($(TARGET_HAS_TEE),false)
PRODUCT_COPY_FILES += \
    vendor/amlogic/gx-common/proprietary/vendor/bin/tee-supplicant:$(TARGET_COPY_OUT_VENDOR)/bin/tee-supplicant \
    vendor/amlogic/gx-common/proprietary/vendor/bin/tee_preload_fw:$(TARGET_COPY_OUT_VENDOR)/bin/tee_preload_fw \
    vendor/amlogic/gx-common/proprietary/vendor/etc/init/tee-supplicant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee-supplicant.rc \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libsecmem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecmem.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libtee_load_video_fw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtee_load_video_fw.so \
    vendor/amlogic/gx-common/proprietary/vendor/lib/libteec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libteec.so
endif
