# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/ne-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter s4 sc2 t7,$(TARGET_AMLOGIC_SOC)),)

endif
