# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/g12-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter g12a g12b sm1,$(TARGET_AMLOGIC_SOC)),)

endif
